services:
  cgw:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 5g-agw-cgw
    restart: unless-stopped
    environment:
      CGW_LISTEN_ADDR: ${CGW_LISTEN_ADDR:-0.0.0.0:38412}
      CGW_AMF_ADDR: ${CGW_AMF_ADDR:-}
    # 将来の拡張のため、コンテナに固定IPを振れる独自のネットワークを定義しておきます
    networks:
      sbi_network:
        ipv4_address: 10.100.200.10

  packetrusher:
    build:
      context: .
      dockerfile: Dockerfile.pr
    container_name: 5g-agw-packetrusher
    command: ./packetrusher ${PACKETRUSHER_CMD:-gnb}
    depends_on:
      - cgw
    volumes:
      - ./config/packetrusher.yaml:/app/config/config.yml
    networks:
      sbi_network:
        ipv4_address: 10.100.200.20

networks:
  sbi_network:
    name: sbi_network
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.200.0/24
